# Generated by Django 4.2.7 on 2023-12-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='descr',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
