# Generated by Django 4.2.7 on 2023-12-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_item_descr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='descr',
            field=models.CharField(blank=True, default='нет описания', max_length=500),
        ),
    ]
